point_cloud_topic: "/cloud"
map_frame_id: "/map"
robot_base_frame_id: "/laser"
robot_pose_with_covariance_topic: "/laser"
robot_pose_cache_size: 200
track_point_frame_id: "laser"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
